export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_SUCCESS = "FETCH_BLOGS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";

export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_START = "CREATE_POST_START";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_START = "DELETE_POST_START";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const FETCH_POST_DETAIL = "FETCH_POST_DETAIL";
export const FETCH_POST_DETAIL_START = "FETCH_POST_DETAIL_START";
export const FETCH_POST_DETAIL_SUCCESS = "FETCH_POST_DETAIL_SUCCESS";
export const FETCH_POST_DETAIL_FAIL = "FETCH_POST_DETAIL_FAIL";

export const SAVE_EDIT = "SAVE_EDIT";
export const SAVE_EDIT_START = "SAVE_EDIT_START";
export const SAVE_EDIT_SUCCESS = "SAVE_EDIT_SUCCESS";
export const SAVE_EDIT_FAIL = "SAVE_EDIT_FAIL";

export const CREATE_COMMENT = "CREATE_COMMENT";
export const CREATE_COMMENT_START = "CREATE_COMMENT_START";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";
